services:
  - type: web
    name: dark-cinema
    env: node
    plan: free
    buildCommand: |
      apt-get update -y
      apt-get install -y ffmpeg
      npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 22.4.0
    healthCheckPath: /api/status
